name: CI-CD Pipeine to AWS ElastocBeanstalk
env: 
  EB_PACKAGE_S3_BUCKET_NAME  : "github-actions-pipeline-bootstrap-app-packages"
  EB_APPLICATION_NAME        : "my-bootstrap-app"
  EB_ENVIRONMENT_NAME        : "My-bootstrap-app-env"
  DEPLOY_PACKAGE_NAME        :  "my_app_${{ github.sha }}.zip"
  AWS_REGION_NAME            :  "us-east-1"
on: 
  push: 
    branches:
      - master
jobs: 
  ci_part: 
    runs-on: ubuntu-latest

    steps: 
      - name: Git clone our repo
        uses: actions/checkout@v1

      - name: Create ZIP deployment package 
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
